variables:
  CI_PLUGIN: SaveExtension

image: $CI_REGISTRY/piperift/ue4-full:4.26.0

stages:
  - build
  - test
  - package

cache:
  paths:
    - Build/

before_script:
  # Download Piperift's CICD scripts
  - git clone https://github.com/PipeRift/CICDScripts Lib

build:
  stage: build
  tags: [docker, ue4]
  script:
    - cd Lib
    - py build.py plugin

test:
  stage: test
  tags: [docker, ue4]
  script:
    - cd Lib
    - py test.py plugin
  artifacts:
    paths:
      - Test/Report.xml
    reports:
      junit: Test/Report.xml

upload:
  stage: package
  script:
    - cd Lib
    - py compress.py plugin
    - py vault.py upload
